import { Session, Lead, PaymentType, ClientSource, LeadSource } from '../types';

export const mockSessions: Session[] = [
  {
    "id": "s_mock_1",
    "clientNumber": "001",
    "clientName": "Sanjay Bista",
    "clientEmail": "sanjay.bista@example.com",
    "clientPhone": "9863137352",
    "sessionType": "Maternity Photography",
    "date": "2026-03-22",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "57 Edited Photos",
    "deliverableDueDate": "2026-04-01",
    "isDelivered": true,
    "source": ClientSource.OTHER,
    "package": "Premium Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 29000,
      "depositAmount": 14500,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1773035684451
  },
  {
    "id": "s_mock_2",
    "clientNumber": "002",
    "clientName": "Srijana Tamang",
    "clientEmail": "srijana.tamang@example.com",
    "clientPhone": "9822623302",
    "sessionType": "Cake Smash",
    "date": "2026-04-01",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "27 Edited Photos",
    "deliverableDueDate": "2026-04-16",
    "isDelivered": true,
    "babyBirthday": "2025-04-01",
    "source": ClientSource.REFERRAL,
    "package": "Deluxe Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 20000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1773986084451
  },
  {
    "id": "s_mock_3",
    "clientNumber": "003",
    "clientName": "Puja Maharjan",
    "clientEmail": "puja.maharjan@example.com",
    "clientPhone": "9837312600",
    "sessionType": "Cake Smash",
    "date": "2026-04-21",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "17 Edited Photos",
    "deliverableDueDate": "2026-05-11",
    "isDelivered": false,
    "babyBirthday": "2025-04-21",
    "source": ClientSource.OTHER,
    "package": "Deluxe Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 10000,
      "depositAmount": 5000,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1775454884451
  },
  {
    "id": "s_mock_4",
    "clientNumber": "004",
    "clientName": "Saurav Shah",
    "clientEmail": "",
    "clientPhone": "9892372607",
    "sessionType": "Maternity Photography",
    "date": "2026-02-28",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "54 Edited Photos",
    "deliverableDueDate": "2026-03-10",
    "isDelivered": true,
    "source": ClientSource.OTHER,
    "package": "Premium Maternity Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 30000,
      "depositAmount": 15000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1770443684451
  },
  {
    "id": "s_mock_5",
    "clientNumber": "005",
    "clientName": "Manisha Sharma",
    "clientEmail": "manisha.sharma@example.com",
    "clientPhone": "9868871150",
    "sessionType": "Cake Smash",
    "date": "2026-04-16",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "47 Edited Photos",
    "deliverableDueDate": "2026-04-27",
    "isDelivered": false,
    "babyBirthday": "2025-04-16",
    "source": ClientSource.REFERRAL,
    "package": "Basic Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 25000,
      "depositAmount": 12500,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1775886884451
  },
  {
    "id": "s_mock_6",
    "clientNumber": "006",
    "clientName": "Kabita Gurung",
    "clientEmail": "kabita.gurung@example.com",
    "clientPhone": "9824375975",
    "sessionType": "Family Portrait",
    "date": "2026-03-09",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "31 Edited Photos",
    "deliverableDueDate": "2026-03-18",
    "isDelivered": true,
    "source": ClientSource.ADS,
    "package": "Basic Family Session",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 20000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1772085284451
  },
  {
    "id": "s_mock_7",
    "clientNumber": "007",
    "clientName": "Kriti Chaudhary",
    "clientEmail": "kriti.chaudhary@example.com",
    "clientPhone": "9858470311",
    "sessionType": "Maternity Photography",
    "date": "2026-04-12",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "56 Edited Photos",
    "deliverableDueDate": "2026-04-26",
    "isDelivered": false,
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Premium Maternity Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 23000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1774677284451
  },
  {
    "id": "s_mock_8",
    "clientNumber": "008",
    "clientName": "Suman Magar",
    "clientEmail": "",
    "clientPhone": "9881648645",
    "sessionType": "Family Portrait",
    "date": "2026-05-14",
    "startTime": "15:00",
    "endTime": "17:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "19 Edited Photos",
    "deliverableDueDate": "2026-06-04",
    "isDelivered": false,
    "source": ClientSource.REFERRAL,
    "package": "Standard Family Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 34000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1776491684451
  },
  {
    "id": "s_mock_9",
    "clientNumber": "009",
    "clientName": "Ramesh Gurung",
    "clientEmail": "",
    "clientPhone": "9874550246",
    "sessionType": "Maternity Photography",
    "date": "2026-04-09",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "16 Edited Photos",
    "deliverableDueDate": "2026-04-30",
    "isDelivered": false,
    "source": ClientSource.ADS,
    "package": "Premium Maternity Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 33000,
      "depositAmount": 16500,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1774418084451
  },
  {
    "id": "s_mock_10",
    "clientNumber": "010",
    "clientName": "Santosh KC",
    "clientEmail": "santosh.kc@example.com",
    "clientPhone": "9841100966",
    "sessionType": "Cake Smash",
    "date": "2026-03-02",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "40 Edited Photos",
    "deliverableDueDate": "2026-03-12",
    "isDelivered": true,
    "babyBirthday": "2025-03-02",
    "source": ClientSource.WALK_IN,
    "package": "Deluxe Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 34000,
      "depositAmount": 17000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1770011684451
  },
  {
    "id": "s_mock_11",
    "clientNumber": "011",
    "clientName": "Rajendra Rai",
    "clientEmail": "",
    "clientPhone": "9848583642",
    "sessionType": "Newborn Photography",
    "date": "2026-04-05",
    "startTime": "14:00",
    "endTime": "16:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "39 Edited Photos",
    "deliverableDueDate": "2026-04-23",
    "isDelivered": true,
    "source": ClientSource.OTHER,
    "package": "Standard Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 15000,
      "depositAmount": 7500,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1774245284451
  },
  {
    "id": "s_mock_12",
    "clientNumber": "012",
    "clientName": "Binod KC",
    "clientEmail": "",
    "clientPhone": "9856333722",
    "sessionType": "Maternity Photography",
    "date": "2026-04-01",
    "startTime": "14:00",
    "endTime": "16:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "31 Edited Photos",
    "deliverableDueDate": "2026-04-09",
    "isDelivered": true,
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Standard Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 30000,
      "depositAmount": 15000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1774245284451
  },
  {
    "id": "s_mock_13",
    "clientNumber": "013",
    "clientName": "Puja Magar",
    "clientEmail": "",
    "clientPhone": "9886465120",
    "sessionType": "Maternity Photography",
    "date": "2026-04-02",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "39 Edited Photos",
    "deliverableDueDate": "2026-04-15",
    "isDelivered": true,
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Premium Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 23000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1772949284451
  },
  {
    "id": "s_mock_14",
    "clientNumber": "014",
    "clientName": "Prakash Maharjan",
    "clientEmail": "",
    "clientPhone": "9836997079",
    "sessionType": "Cake Smash",
    "date": "2026-05-29",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "52 Edited Photos",
    "deliverableDueDate": "2026-06-17",
    "isDelivered": false,
    "babyBirthday": "2025-05-29",
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Deluxe Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 15000,
      "depositAmount": 7500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1778565284451
  },
  {
    "id": "s_mock_15",
    "clientNumber": "015",
    "clientName": "Santosh Shrestha",
    "clientEmail": "santosh.shrestha@example.com",
    "clientPhone": "9871007020",
    "sessionType": "Cake Smash",
    "date": "2026-03-28",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "30 Edited Photos",
    "deliverableDueDate": "2026-04-14",
    "isDelivered": true,
    "babyBirthday": "2025-03-28",
    "source": ClientSource.ADS,
    "package": "Basic Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 17000,
      "depositAmount": 8500,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1773813284451
  },
  {
    "id": "s_mock_16",
    "clientNumber": "016",
    "clientName": "Milan Magar",
    "clientEmail": "",
    "clientPhone": "9834776423",
    "sessionType": "Newborn Photography",
    "date": "2026-05-11",
    "startTime": "13:00",
    "endTime": "15:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "42 Edited Photos",
    "deliverableDueDate": "2026-05-23",
    "isDelivered": false,
    "source": ClientSource.REFERRAL,
    "package": "Basic Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 18000,
      "depositAmount": 9000,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1776664484451
  },
  {
    "id": "s_mock_17",
    "clientNumber": "017",
    "clientName": "Srijana Gurung",
    "clientEmail": "srijana.gurung@example.com",
    "clientPhone": "9825475304",
    "sessionType": "Maternity Photography",
    "date": "2026-05-08",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "29 Edited Photos",
    "deliverableDueDate": "2026-05-25",
    "isDelivered": false,
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Premium Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 31000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1777701284451
  },
  {
    "id": "s_mock_18",
    "clientNumber": "018",
    "clientName": "Milan Karki",
    "clientEmail": "",
    "clientPhone": "9874343053",
    "sessionType": "Newborn Photography",
    "date": "2026-03-21",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "44 Edited Photos",
    "deliverableDueDate": "2026-03-29",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Basic Newborn Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 32000,
      "depositAmount": 16000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1771566884451
  },
  {
    "id": "s_mock_19",
    "clientNumber": "019",
    "clientName": "Kabita Oli",
    "clientEmail": "kabita.oli@example.com",
    "clientPhone": "9883882683",
    "sessionType": "Cake Smash",
    "date": "2026-05-26",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "55 Edited Photos",
    "deliverableDueDate": "2026-06-09",
    "isDelivered": false,
    "babyBirthday": "2025-05-26",
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Deluxe Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 25000,
      "depositAmount": 12500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1779083684451
  },
  {
    "id": "s_mock_20",
    "clientNumber": "020",
    "clientName": "Suman Sharma",
    "clientEmail": "suman.sharma@example.com",
    "clientPhone": "9866206223",
    "sessionType": "Family Portrait",
    "date": "2026-04-10",
    "startTime": "14:00",
    "endTime": "16:00",
    "isCustomSlot": false,
    "isDeleted": true,
    "deliverables": "35 Edited Photos",
    "deliverableDueDate": "2026-04-30",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Basic Family Session",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 35000,
      "depositAmount": 17500,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1773986084451
  },
  {
    "id": "s_mock_21",
    "clientNumber": "021",
    "clientName": "Rajendra Bhattarai",
    "clientEmail": "",
    "clientPhone": "9838565347",
    "sessionType": "Newborn Photography",
    "date": "2026-04-05",
    "startTime": "15:00",
    "endTime": "17:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "16 Edited Photos",
    "deliverableDueDate": "2026-04-12",
    "isDelivered": true,
    "source": ClientSource.OTHER,
    "package": "Premium Newborn Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 29000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1772949284451
  },
  {
    "id": "s_mock_22",
    "clientNumber": "022",
    "clientName": "Rajendra Shah",
    "clientEmail": "rajendra.shah@example.com",
    "clientPhone": "9817721438",
    "sessionType": "Family Portrait",
    "date": "2026-03-17",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "59 Edited Photos",
    "deliverableDueDate": "2026-03-28",
    "isDelivered": true,
    "source": ClientSource.OTHER,
    "package": "Deluxe Family Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 10000,
      "depositAmount": 5000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1773208484451
  },
  {
    "id": "s_mock_23",
    "clientNumber": "023",
    "clientName": "Rajendra Oli",
    "clientEmail": "",
    "clientPhone": "9829241424",
    "sessionType": "Cake Smash",
    "date": "2026-05-15",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "46 Edited Photos",
    "deliverableDueDate": "2026-06-03",
    "isDelivered": false,
    "babyBirthday": "2025-05-15",
    "source": ClientSource.OTHER,
    "package": "Basic Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 26000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1776750884451
  },
  {
    "id": "s_mock_24",
    "clientNumber": "024",
    "clientName": "Milan Shah",
    "clientEmail": "milan.shah@example.com",
    "clientPhone": "9887891906",
    "sessionType": "Cake Smash",
    "date": "2026-03-24",
    "startTime": "13:00",
    "endTime": "15:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "34 Edited Photos",
    "deliverableDueDate": "2026-04-05",
    "isDelivered": false,
    "babyBirthday": "2025-03-24",
    "source": ClientSource.REFERRAL,
    "package": "Basic Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 13000,
      "depositAmount": 6500,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1772085284451
  },
  {
    "id": "s_mock_25",
    "clientNumber": "025",
    "clientName": "Saurav Bista",
    "clientEmail": "saurav.bista@example.com",
    "clientPhone": "9895764416",
    "sessionType": "Maternity Photography",
    "date": "2026-03-06",
    "startTime": "15:00",
    "endTime": "17:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "38 Edited Photos",
    "deliverableDueDate": "2026-03-25",
    "isDelivered": true,
    "source": ClientSource.REFERRAL,
    "package": "Premium Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 27000,
      "depositAmount": 13500,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1771048484451
  },
  {
    "id": "s_mock_26",
    "clientNumber": "026",
    "clientName": "Manisha Bhattarai",
    "clientEmail": "manisha.bhattarai@example.com",
    "clientPhone": "9847155429",
    "sessionType": "Newborn Photography",
    "date": "2026-04-21",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "37 Edited Photos",
    "deliverableDueDate": "2026-05-04",
    "isDelivered": false,
    "source": ClientSource.REFERRAL,
    "package": "Standard Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 34000,
      "depositAmount": 17000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1775627684451
  },
  {
    "id": "s_mock_27",
    "clientNumber": "027",
    "clientName": "Sabina Shrestha",
    "clientEmail": "",
    "clientPhone": "9891812716",
    "sessionType": "Family Portrait",
    "date": "2026-03-16",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "30 Edited Photos",
    "deliverableDueDate": "2026-03-25",
    "isDelivered": true,
    "source": ClientSource.ADS,
    "package": "Basic Family Session",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 34000,
      "depositAmount": 17000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1771480484451
  },
  {
    "id": "s_mock_28",
    "clientNumber": "028",
    "clientName": "Rajendra Shrestha",
    "clientEmail": "rajendra.shrestha@example.com",
    "clientPhone": "9882983784",
    "sessionType": "Cake Smash",
    "date": "2026-03-31",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "17 Edited Photos",
    "deliverableDueDate": "2026-04-20",
    "isDelivered": true,
    "babyBirthday": "2025-03-31",
    "source": ClientSource.REFERRAL,
    "package": "Deluxe Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 10000,
      "depositAmount": 5000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1773813284451
  },
  {
    "id": "s_mock_29",
    "clientNumber": "029",
    "clientName": "Alisha Maharjan",
    "clientEmail": "alisha.maharjan@example.com",
    "clientPhone": "9892564517",
    "sessionType": "Cake Smash",
    "date": "2026-03-20",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "33 Edited Photos",
    "deliverableDueDate": "2026-04-03",
    "isDelivered": true,
    "babyBirthday": "2025-03-20",
    "source": ClientSource.WALK_IN,
    "package": "Basic Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 27000,
      "depositAmount": 13500,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1772344484451
  },
  {
    "id": "s_mock_30",
    "clientNumber": "030",
    "clientName": "Sneha Maharjan",
    "clientEmail": "",
    "clientPhone": "9873671648",
    "sessionType": "Newborn Photography",
    "date": "2026-03-30",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "55 Edited Photos",
    "deliverableDueDate": "2026-04-06",
    "isDelivered": true,
    "source": ClientSource.ADS,
    "package": "Premium Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 23000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1772430884451
  },
  {
    "id": "s_mock_31",
    "clientNumber": "031",
    "clientName": "Binod Rai",
    "clientEmail": "binod.rai@example.com",
    "clientPhone": "9842514783",
    "sessionType": "Family Portrait",
    "date": "2026-05-11",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "32 Edited Photos",
    "deliverableDueDate": "2026-05-18",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Deluxe Family Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 19000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1776491684451
  },
  {
    "id": "s_mock_32",
    "clientNumber": "032",
    "clientName": "Suman Shah",
    "clientEmail": "",
    "clientPhone": "9866037149",
    "sessionType": "Cake Smash",
    "date": "2026-04-19",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": false,
    "isDeleted": true,
    "deliverables": "44 Edited Photos",
    "deliverableDueDate": "2026-05-09",
    "isDelivered": false,
    "babyBirthday": "2025-04-19",
    "source": ClientSource.REFERRAL,
    "package": "Deluxe Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 29000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1776146084451
  },
  {
    "id": "s_mock_33",
    "clientNumber": "033",
    "clientName": "Suman Magar",
    "clientEmail": "",
    "clientPhone": "9881777781",
    "sessionType": "Maternity Photography",
    "date": "2026-05-28",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "37 Edited Photos",
    "deliverableDueDate": "2026-06-04",
    "isDelivered": false,
    "source": ClientSource.REFERRAL,
    "package": "Standard Maternity Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 11000,
      "depositAmount": 5500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1778824484451
  },
  {
    "id": "s_mock_34",
    "clientNumber": "034",
    "clientName": "Prakash Tamang",
    "clientEmail": "",
    "clientPhone": "9815389049",
    "sessionType": "Cake Smash",
    "date": "2026-03-10",
    "startTime": "13:00",
    "endTime": "15:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "25 Edited Photos",
    "deliverableDueDate": "2026-03-17",
    "isDelivered": true,
    "babyBirthday": "2025-03-10",
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Basic Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 32000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1771394084452
  },
  {
    "id": "s_mock_35",
    "clientNumber": "035",
    "clientName": "Manisha Bhattarai",
    "clientEmail": "manisha.bhattarai@example.com",
    "clientPhone": "9873502381",
    "sessionType": "Family Portrait",
    "date": "2026-04-24",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "31 Edited Photos",
    "deliverableDueDate": "2026-05-09",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Basic Family Session",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 17000,
      "depositAmount": 8500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1775022884452
  },
  {
    "id": "s_mock_36",
    "clientNumber": "036",
    "clientName": "Kriti Khadka",
    "clientEmail": "kriti.khadka@example.com",
    "clientPhone": "9871640502",
    "sessionType": "Newborn Photography",
    "date": "2026-02-21",
    "startTime": "17:00",
    "endTime": "19:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "15 Edited Photos",
    "deliverableDueDate": "2026-03-01",
    "isDelivered": true,
    "source": ClientSource.REFERRAL,
    "package": "Premium Newborn Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 13000,
      "depositAmount": 6500,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1770962084452
  },
  {
    "id": "s_mock_37",
    "clientNumber": "037",
    "clientName": "Rita KC",
    "clientEmail": "rita.kc@example.com",
    "clientPhone": "9823036656",
    "sessionType": "Cake Smash",
    "date": "2026-03-07",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "32 Edited Photos",
    "deliverableDueDate": "2026-03-24",
    "isDelivered": true,
    "babyBirthday": "2025-03-07",
    "source": ClientSource.OTHER,
    "package": "Deluxe Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 31000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1772085284452
  },
  {
    "id": "s_mock_38",
    "clientNumber": "038",
    "clientName": "Kiran Gautam",
    "clientEmail": "kiran.gautam@example.com",
    "clientPhone": "9893172592",
    "sessionType": "Newborn Photography",
    "date": "2026-02-20",
    "startTime": "13:00",
    "endTime": "15:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "33 Edited Photos",
    "deliverableDueDate": "2026-03-12",
    "isDelivered": true,
    "source": ClientSource.OTHER,
    "package": "Standard Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 24000,
      "depositAmount": 12000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1770443684452
  },
  {
    "id": "s_mock_39",
    "clientNumber": "039",
    "clientName": "Kriti KC",
    "clientEmail": "kriti.kc@example.com",
    "clientPhone": "9864017907",
    "sessionType": "Maternity Photography",
    "date": "2026-02-26",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "40 Edited Photos",
    "deliverableDueDate": "2026-03-13",
    "isDelivered": true,
    "source": ClientSource.ADS,
    "package": "Premium Maternity Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 30000,
      "depositAmount": 15000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1771480484452
  },
  {
    "id": "s_mock_40",
    "clientNumber": "040",
    "clientName": "Binod Maharjan",
    "clientEmail": "binod.maharjan@example.com",
    "clientPhone": "9878596725",
    "sessionType": "Maternity Photography",
    "date": "2026-05-11",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "35 Edited Photos",
    "deliverableDueDate": "2026-05-22",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Standard Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 34000,
      "depositAmount": 17000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1778046884452
  },
  {
    "id": "s_mock_41",
    "clientNumber": "041",
    "clientName": "Sneha Shrestha",
    "clientEmail": "",
    "clientPhone": "9833605949",
    "sessionType": "Family Portrait",
    "date": "2026-03-28",
    "startTime": "17:00",
    "endTime": "19:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "19 Edited Photos",
    "deliverableDueDate": "2026-04-05",
    "isDelivered": true,
    "source": ClientSource.ADS,
    "package": "Basic Family Session",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 16000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1773899684452
  },
  {
    "id": "s_mock_42",
    "clientNumber": "042",
    "clientName": "Prabin Sharma",
    "clientEmail": "prabin.sharma@example.com",
    "clientPhone": "9875211889",
    "sessionType": "Newborn Photography",
    "date": "2026-03-04",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "57 Edited Photos",
    "deliverableDueDate": "2026-03-20",
    "isDelivered": true,
    "source": ClientSource.REFERRAL,
    "package": "Premium Newborn Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 13000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1770270884452
  },
  {
    "id": "s_mock_43",
    "clientNumber": "043",
    "clientName": "Ashish Sharma",
    "clientEmail": "ashish.sharma@example.com",
    "clientPhone": "9839637490",
    "sessionType": "Cake Smash",
    "date": "2026-05-16",
    "startTime": "14:00",
    "endTime": "16:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "22 Edited Photos",
    "deliverableDueDate": "2026-06-01",
    "isDelivered": false,
    "babyBirthday": "2025-05-16",
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Deluxe Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 33000,
      "depositAmount": 16500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1776318884452
  },
  {
    "id": "s_mock_44",
    "clientNumber": "044",
    "clientName": "Kriti Bista",
    "clientEmail": "kriti.bista@example.com",
    "clientPhone": "9840866648",
    "sessionType": "Maternity Photography",
    "date": "2026-05-27",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "16 Edited Photos",
    "deliverableDueDate": "2026-06-11",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Standard Maternity Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 29000,
      "depositAmount": 14500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1779256484452
  },
  {
    "id": "s_mock_45",
    "clientNumber": "045",
    "clientName": "Santosh Shah",
    "clientEmail": "santosh.shah@example.com",
    "clientPhone": "9814618441",
    "sessionType": "Cake Smash",
    "date": "2026-05-15",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "20 Edited Photos",
    "deliverableDueDate": "2026-05-22",
    "isDelivered": false,
    "babyBirthday": "2025-05-15",
    "source": ClientSource.OTHER,
    "package": "Deluxe Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 33000,
      "depositAmount": 16500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1777528484452
  },
  {
    "id": "s_mock_46",
    "clientNumber": "046",
    "clientName": "Prabin Bista",
    "clientEmail": "prabin.bista@example.com",
    "clientPhone": "9844665917",
    "sessionType": "Newborn Photography",
    "date": "2026-02-24",
    "startTime": "14:00",
    "endTime": "16:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "49 Edited Photos",
    "deliverableDueDate": "2026-03-12",
    "isDelivered": true,
    "source": ClientSource.OTHER,
    "package": "Standard Newborn Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 28000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1769666084452
  },
  {
    "id": "s_mock_47",
    "clientNumber": "047",
    "clientName": "Nita Rai",
    "clientEmail": "nita.rai@example.com",
    "clientPhone": "9836359615",
    "sessionType": "Family Portrait",
    "date": "2026-03-21",
    "startTime": "17:00",
    "endTime": "19:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "43 Edited Photos",
    "deliverableDueDate": "2026-04-03",
    "isDelivered": true,
    "source": ClientSource.REFERRAL,
    "package": "Basic Family Session",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 19000,
      "depositAmount": 9500,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1773381284452
  },
  {
    "id": "s_mock_48",
    "clientNumber": "048",
    "clientName": "Anish Gautam",
    "clientEmail": "anish.gautam@example.com",
    "clientPhone": "9886926823",
    "sessionType": "Cake Smash",
    "date": "2026-05-06",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "30 Edited Photos",
    "deliverableDueDate": "2026-05-26",
    "isDelivered": false,
    "babyBirthday": "2025-05-06",
    "source": ClientSource.ADS,
    "package": "Deluxe Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 33000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1776923684452
  },
  {
    "id": "s_mock_49",
    "clientNumber": "049",
    "clientName": "Nita KC",
    "clientEmail": "",
    "clientPhone": "9884650059",
    "sessionType": "Cake Smash",
    "date": "2026-03-16",
    "startTime": "15:00",
    "endTime": "17:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "33 Edited Photos",
    "deliverableDueDate": "2026-03-24",
    "isDelivered": true,
    "babyBirthday": "2025-03-16",
    "source": ClientSource.REFERRAL,
    "package": "Deluxe Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 32000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1772430884452
  },
  {
    "id": "s_mock_50",
    "clientNumber": "050",
    "clientName": "Nita Shah",
    "clientEmail": "nita.shah@example.com",
    "clientPhone": "9862880139",
    "sessionType": "Cake Smash",
    "date": "2026-04-16",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "60 Edited Photos",
    "deliverableDueDate": "2026-04-28",
    "isDelivered": false,
    "babyBirthday": "2025-04-16",
    "source": ClientSource.OTHER,
    "package": "Deluxe Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 29000,
      "depositAmount": 14500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1775195684452
  },
  {
    "id": "s_mock_51",
    "clientNumber": "051",
    "clientName": "Kabita Oli",
    "clientEmail": "",
    "clientPhone": "9843572686",
    "sessionType": "Family Portrait",
    "date": "2026-04-09",
    "startTime": "14:00",
    "endTime": "16:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "35 Edited Photos",
    "deliverableDueDate": "2026-04-18",
    "isDelivered": false,
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Deluxe Family Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 19000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1774850084452
  },
  {
    "id": "s_mock_52",
    "clientNumber": "052",
    "clientName": "Niranjan Lama",
    "clientEmail": "",
    "clientPhone": "9898559019",
    "sessionType": "Maternity Photography",
    "date": "2026-04-04",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "60 Edited Photos",
    "deliverableDueDate": "2026-04-22",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Premium Maternity Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 15000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1772776484452
  },
  {
    "id": "s_mock_53",
    "clientNumber": "053",
    "clientName": "Sneha Magar",
    "clientEmail": "sneha.magar@example.com",
    "clientPhone": "9832400716",
    "sessionType": "Newborn Photography",
    "date": "2026-02-27",
    "startTime": "14:00",
    "endTime": "16:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "33 Edited Photos",
    "deliverableDueDate": "2026-03-09",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Standard Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 32000,
      "depositAmount": 16000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1771566884452
  },
  {
    "id": "s_mock_54",
    "clientNumber": "054",
    "clientName": "Rita Shah",
    "clientEmail": "rita.shah@example.com",
    "clientPhone": "9868984061",
    "sessionType": "Family Portrait",
    "date": "2026-03-16",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "53 Edited Photos",
    "deliverableDueDate": "2026-03-30",
    "isDelivered": true,
    "source": ClientSource.WALK_IN,
    "package": "Deluxe Family Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 29000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1773122084452
  },
  {
    "id": "s_mock_55",
    "clientNumber": "055",
    "clientName": "Manisha Magar",
    "clientEmail": "manisha.magar@example.com",
    "clientPhone": "9839558048",
    "sessionType": "Maternity Photography",
    "date": "2026-04-03",
    "startTime": "15:00",
    "endTime": "17:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "60 Edited Photos",
    "deliverableDueDate": "2026-04-14",
    "isDelivered": true,
    "source": ClientSource.WALK_IN,
    "package": "Premium Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 30000,
      "depositAmount": 15000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1774504484452
  },
  {
    "id": "s_mock_56",
    "clientNumber": "056",
    "clientName": "Saurav Bhattarai",
    "clientEmail": "saurav.bhattarai@example.com",
    "clientPhone": "9832428496",
    "sessionType": "Maternity Photography",
    "date": "2026-03-06",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "31 Edited Photos",
    "deliverableDueDate": "2026-03-23",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Premium Maternity Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 27000,
      "depositAmount": 13500,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1772258084452
  },
  {
    "id": "s_mock_57",
    "clientNumber": "057",
    "clientName": "Kiran Shah",
    "clientEmail": "kiran.shah@example.com",
    "clientPhone": "9869343337",
    "sessionType": "Family Portrait",
    "date": "2026-05-20",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "19 Edited Photos",
    "deliverableDueDate": "2026-05-28",
    "isDelivered": false,
    "source": ClientSource.REFERRAL,
    "package": "Deluxe Family Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 34000,
      "depositAmount": 17000,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1777269284452
  },
  {
    "id": "s_mock_58",
    "clientNumber": "058",
    "clientName": "Manisha Lama",
    "clientEmail": "manisha.lama@example.com",
    "clientPhone": "9826814901",
    "sessionType": "Newborn Photography",
    "date": "2026-04-26",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "41 Edited Photos",
    "deliverableDueDate": "2026-05-10",
    "isDelivered": false,
    "source": ClientSource.ADS,
    "package": "Standard Newborn Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 29000,
      "depositAmount": 14500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1776750884452
  },
  {
    "id": "s_mock_59",
    "clientNumber": "059",
    "clientName": "Rita Pandey",
    "clientEmail": "rita.pandey@example.com",
    "clientPhone": "9860643581",
    "sessionType": "Maternity Photography",
    "date": "2026-03-22",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "43 Edited Photos",
    "deliverableDueDate": "2026-03-30",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Premium Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 14000,
      "depositAmount": 7000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1771826084452
  },
  {
    "id": "s_mock_60",
    "clientNumber": "060",
    "clientName": "Prakash Gurung",
    "clientEmail": "prakash.gurung@example.com",
    "clientPhone": "9858262205",
    "sessionType": "Cake Smash",
    "date": "2026-03-13",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "35 Edited Photos",
    "deliverableDueDate": "2026-03-29",
    "isDelivered": true,
    "babyBirthday": "2025-03-13",
    "source": ClientSource.OTHER,
    "package": "Basic Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 18000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1771912484452
  },
  {
    "id": "s_mock_61",
    "clientNumber": "061",
    "clientName": "Saurav KC",
    "clientEmail": "saurav.kc@example.com",
    "clientPhone": "9837822926",
    "sessionType": "Newborn Photography",
    "date": "2026-05-21",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "52 Edited Photos",
    "deliverableDueDate": "2026-06-03",
    "isDelivered": false,
    "source": ClientSource.ADS,
    "package": "Basic Newborn Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 16000,
      "depositAmount": 8000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1776750884452
  },
  {
    "id": "s_mock_62",
    "clientNumber": "062",
    "clientName": "Kriti Lama",
    "clientEmail": "kriti.lama@example.com",
    "clientPhone": "9817555911",
    "sessionType": "Cake Smash",
    "date": "2026-03-08",
    "startTime": "17:00",
    "endTime": "19:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "52 Edited Photos",
    "deliverableDueDate": "2026-03-24",
    "isDelivered": false,
    "babyBirthday": "2025-03-08",
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Basic Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 16000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1771048484452
  },
  {
    "id": "s_mock_63",
    "clientNumber": "063",
    "clientName": "Bikash Thapa",
    "clientEmail": "",
    "clientPhone": "9867986098",
    "sessionType": "Family Portrait",
    "date": "2026-05-09",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "40 Edited Photos",
    "deliverableDueDate": "2026-05-23",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Basic Family Session",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 13000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1777269284452
  },
  {
    "id": "s_mock_64",
    "clientNumber": "064",
    "clientName": "Milan Thapa",
    "clientEmail": "milan.thapa@example.com",
    "clientPhone": "9886288970",
    "sessionType": "Cake Smash",
    "date": "2026-04-20",
    "startTime": "17:00",
    "endTime": "19:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "38 Edited Photos",
    "deliverableDueDate": "2026-05-06",
    "isDelivered": false,
    "babyBirthday": "2025-04-20",
    "source": ClientSource.WALK_IN,
    "package": "Deluxe Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 33000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1775714084452
  },
  {
    "id": "s_mock_65",
    "clientNumber": "065",
    "clientName": "Ashish Gurung",
    "clientEmail": "",
    "clientPhone": "9861807386",
    "sessionType": "Maternity Photography",
    "date": "2026-05-27",
    "startTime": "15:00",
    "endTime": "17:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "19 Edited Photos",
    "deliverableDueDate": "2026-06-05",
    "isDelivered": false,
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Premium Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 14000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1777442084452
  }
];

export const mockLeads: Lead[] = [
  {
    "id": "l_mock_1",
    "name": "Binod Maharjan",
    "phone": "9822113787",
    "email": "binod.maharjan@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-05-02",
    "createdAt": "2026-04-25T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_2",
    "name": "Ashish Karki",
    "phone": "9871528844",
    "email": "",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-03-31",
    "createdAt": "2026-03-24T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_3",
    "name": "Diya Karki",
    "phone": "9810482252",
    "email": "",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-08",
    "createdAt": "2026-04-06T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_4",
    "name": "Ashish KC",
    "phone": "9839212319",
    "email": "",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-03",
    "createdAt": "2026-03-31T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_5",
    "name": "Prakash Bista",
    "phone": "9867022982",
    "email": "",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-03-31",
    "createdAt": "2026-03-30T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_6",
    "name": "Alisha Adhikari",
    "phone": "9895758631",
    "email": "alisha.adhikari@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-14",
    "createdAt": "2026-04-11T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_7",
    "name": "Bimala Adhikari",
    "phone": "9852835923",
    "email": "bimala.adhikari@example.com",
    "source": LeadSource.WALK_IN,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-19",
    "createdAt": "2026-04-14T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_8",
    "name": "Milan Adhikari",
    "phone": "9854104595",
    "email": "milan.adhikari@example.com",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-18",
    "createdAt": "2026-04-14T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_9",
    "name": "Aarohi Khadka",
    "phone": "9823457553",
    "email": "aarohi.khadka@example.com",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-03-30",
    "createdAt": "2026-03-24T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_10",
    "name": "Puja Maharjan",
    "phone": "9867325842",
    "email": "puja.maharjan@example.com",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-03-30",
    "createdAt": "2026-03-24T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_11",
    "name": "Srijana Lama",
    "phone": "9863535052",
    "email": "srijana.lama@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-22",
    "createdAt": "2026-04-15T05:54:44.452Z",
    "isDeleted": true
  },
  {
    "id": "l_mock_12",
    "name": "Santosh Shah",
    "phone": "9894606723",
    "email": "",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-08",
    "createdAt": "2026-04-03T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_13",
    "name": "Santosh Chaudhary",
    "phone": "9817494751",
    "email": "",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-09",
    "createdAt": "2026-04-02T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_14",
    "name": "Suman Thapa",
    "phone": "9894947588",
    "email": "",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-26",
    "createdAt": "2026-04-19T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_15",
    "name": "Sameer Shah",
    "phone": "9819800579",
    "email": "sameer.shah@example.com",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-21",
    "createdAt": "2026-04-20T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_16",
    "name": "Bikash Sharma",
    "phone": "9811383363",
    "email": "",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-15",
    "createdAt": "2026-04-09T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_17",
    "name": "Niranjan Gautam",
    "phone": "9879666151",
    "email": "niranjan.gautam@example.com",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-05-01",
    "createdAt": "2026-04-25T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_18",
    "name": "Sabina Gurung",
    "phone": "9888454524",
    "email": "sabina.gurung@example.com",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-06",
    "createdAt": "2026-04-02T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_19",
    "name": "Bimala Gautam",
    "phone": "9846728936",
    "email": "",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-20",
    "createdAt": "2026-04-16T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_20",
    "name": "Puja Rai",
    "phone": "9845626061",
    "email": "puja.rai@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-13",
    "createdAt": "2026-04-12T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_21",
    "name": "Milan Karki",
    "phone": "9824643417",
    "email": "",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-01",
    "createdAt": "2026-03-25T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_22",
    "name": "Kabita Shah",
    "phone": "9889859980",
    "email": "",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-17",
    "createdAt": "2026-04-15T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_23",
    "name": "Kabita Maharjan",
    "phone": "9884133602",
    "email": "kabita.maharjan@example.com",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-07",
    "createdAt": "2026-03-31T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_24",
    "name": "Ashish KC",
    "phone": "9843493333",
    "email": "ashish.kc@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-03-30",
    "createdAt": "2026-03-27T05:54:44.452Z",
    "isDeleted": true
  },
  {
    "id": "l_mock_25",
    "name": "Nita KC",
    "phone": "9829615150",
    "email": "nita.kc@example.com",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-03-28",
    "createdAt": "2026-03-27T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_26",
    "name": "Kabita Lama",
    "phone": "9877212776",
    "email": "",
    "source": LeadSource.WALK_IN,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-21",
    "createdAt": "2026-04-20T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_27",
    "name": "Rita Gautam",
    "phone": "9829210158",
    "email": "rita.gautam@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-06",
    "createdAt": "2026-04-05T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_28",
    "name": "Kiran Shrestha",
    "phone": "9879414164",
    "email": "",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-27",
    "createdAt": "2026-04-21T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_29",
    "name": "Kiran Rai",
    "phone": "9820147108",
    "email": "kiran.rai@example.com",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-07",
    "createdAt": "2026-04-03T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_30",
    "name": "Niranjan Gautam",
    "phone": "9870022852",
    "email": "",
    "source": LeadSource.WALK_IN,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-03-30",
    "createdAt": "2026-03-25T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_31",
    "name": "Kiran Oli",
    "phone": "9886092737",
    "email": "",
    "source": LeadSource.WALK_IN,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-03-31",
    "createdAt": "2026-03-26T05:54:44.452Z",
    "isDeleted": true
  },
  {
    "id": "l_mock_32",
    "name": "Alisha Oli",
    "phone": "9835832551",
    "email": "alisha.oli@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-26",
    "createdAt": "2026-04-22T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_33",
    "name": "Alisha KC",
    "phone": "9828666069",
    "email": "alisha.kc@example.com",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-03-24",
    "createdAt": "2026-03-23T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_34",
    "name": "Alisha Karki",
    "phone": "9898372937",
    "email": "",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-03-28",
    "createdAt": "2026-03-22T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_35",
    "name": "Roshan Bista",
    "phone": "9863312912",
    "email": "roshan.bista@example.com",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-17",
    "createdAt": "2026-04-13T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_36",
    "name": "Alisha Tamang",
    "phone": "9873002834",
    "email": "",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-02",
    "createdAt": "2026-04-01T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_37",
    "name": "Sanjay Adhikari",
    "phone": "9871749515",
    "email": "sanjay.adhikari@example.com",
    "source": LeadSource.WALK_IN,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-24",
    "createdAt": "2026-04-18T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_38",
    "name": "Roshan Bhattarai",
    "phone": "9847509965",
    "email": "roshan.bhattarai@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-02",
    "createdAt": "2026-03-30T05:54:44.452Z",
    "isDeleted": true
  },
  {
    "id": "l_mock_39",
    "name": "Roshan Shrestha",
    "phone": "9827748115",
    "email": "",
    "source": LeadSource.WALK_IN,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-11",
    "createdAt": "2026-04-06T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_40",
    "name": "Puja Pandey",
    "phone": "9851140749",
    "email": "",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-05",
    "createdAt": "2026-03-29T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_41",
    "name": "Saurav Shah",
    "phone": "9872377796",
    "email": "",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-20",
    "createdAt": "2026-04-17T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_42",
    "name": "Puja Karki",
    "phone": "9838290438",
    "email": "puja.karki@example.com",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-26",
    "createdAt": "2026-04-24T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_43",
    "name": "Milan Shah",
    "phone": "9874203752",
    "email": "milan.shah@example.com",
    "source": LeadSource.WALK_IN,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-03-31",
    "createdAt": "2026-03-29T05:54:44.452Z",
    "isDeleted": true
  },
  {
    "id": "l_mock_44",
    "name": "Kiran Rai",
    "phone": "9876358362",
    "email": "",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-05-02",
    "createdAt": "2026-04-26T05:54:44.452Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_45",
    "name": "Prakash Magar",
    "phone": "9868503030",
    "email": "",
    "source": LeadSource.WALK_IN,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-09",
    "createdAt": "2026-04-02T05:54:44.452Z",
    "isDeleted": false
  }
];
