import { Session, Lead, PaymentType, ClientSource, LeadSource } from '../types';

export const mockSessions: Session[] = [
  {
    "id": "s_mock_1",
    "clientNumber": "001",
    "clientName": "Sanjay Tamang",
    "clientEmail": "",
    "clientPhone": "9848835976",
    "sessionType": "Family Portrait",
    "date": "2026-04-21",
    "startTime": "14:00",
    "endTime": "16:00",
    "isCustomSlot": false,
    "isDeleted": true,
    "deliverables": "28 Edited Photos",
    "deliverableDueDate": "2026-05-06",
    "isDelivered": false,
    "source": ClientSource.REFERRAL,
    "package": "Standard Family Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 17000,
      "depositAmount": 8500,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1774935855587
  },
  {
    "id": "s_mock_2",
    "clientNumber": "002",
    "clientName": "Srijana Sharma",
    "clientEmail": "srijana.sharma@example.com",
    "clientPhone": "9835657429",
    "sessionType": "Newborn Photography",
    "date": "2026-03-26",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "15 Edited Photos",
    "deliverableDueDate": "2026-04-03",
    "isDelivered": false,
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Basic Newborn Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 35000,
      "remainingPaid": true
    },
    "createdAt": 1771911855587
  },
  {
    "id": "s_mock_3",
    "clientNumber": "003",
    "clientName": "Sabina Oli",
    "clientEmail": "sabina.oli@example.com",
    "clientPhone": "9830998860",
    "sessionType": "Family Portrait",
    "date": "2026-05-17",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "57 Edited Photos",
    "deliverableDueDate": "2026-05-25",
    "isDelivered": false,
    "source": ClientSource.ADS,
    "package": "Standard Family Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 30000,
      "remainingPaid": false
    },
    "createdAt": 1777268655587
  },
  {
    "id": "s_mock_4",
    "clientNumber": "004",
    "clientName": "Ramesh Shrestha",
    "clientEmail": "ramesh.shrestha@example.com",
    "clientPhone": "9821157437",
    "sessionType": "Cake Smash",
    "date": "2026-05-08",
    "startTime": "13:00",
    "endTime": "15:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "58 Edited Photos",
    "deliverableDueDate": "2026-05-29",
    "isDelivered": false,
    "babyBirthday": "2025-05-08",
    "source": ClientSource.OTHER,
    "package": "Basic Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 12000,
      "remainingPaid": true
    },
    "createdAt": 1775713455587
  },
  {
    "id": "s_mock_5",
    "clientNumber": "005",
    "clientName": "Kriti Shrestha",
    "clientEmail": "kriti.shrestha@example.com",
    "clientPhone": "9881706713",
    "sessionType": "Newborn Photography",
    "date": "2026-06-01",
    "startTime": "17:00",
    "endTime": "19:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "17 Edited Photos",
    "deliverableDueDate": "2026-06-20",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Premium Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 20000,
      "remainingPaid": false
    },
    "createdAt": 1778737455587
  },
  {
    "id": "s_mock_6",
    "clientNumber": "006",
    "clientName": "Milan Shrestha",
    "clientEmail": "",
    "clientPhone": "9899368052",
    "sessionType": "Family Portrait",
    "date": "2026-04-22",
    "startTime": "13:00",
    "endTime": "15:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "51 Edited Photos",
    "deliverableDueDate": "2026-04-30",
    "isDelivered": false,
    "source": ClientSource.ADS,
    "package": "Deluxe Family Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 35000,
      "depositAmount": 17500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1776318255587
  },
  {
    "id": "s_mock_7",
    "clientNumber": "007",
    "clientName": "Sanjay Oli",
    "clientEmail": "sanjay.oli@example.com",
    "clientPhone": "9872958653",
    "sessionType": "Cake Smash",
    "date": "2026-03-31",
    "startTime": "13:00",
    "endTime": "15:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "34 Edited Photos",
    "deliverableDueDate": "2026-04-21",
    "isDelivered": true,
    "babyBirthday": "2025-03-31",
    "source": ClientSource.OTHER,
    "package": "Basic Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 26000,
      "depositAmount": 13000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1774331055587
  },
  {
    "id": "s_mock_8",
    "clientNumber": "008",
    "clientName": "Rajendra KC",
    "clientEmail": "rajendra.kc@example.com",
    "clientPhone": "9859839442",
    "sessionType": "Newborn Photography",
    "date": "2026-04-14",
    "startTime": "17:00",
    "endTime": "19:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "51 Edited Photos",
    "deliverableDueDate": "2026-05-03",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Basic Newborn Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 16000,
      "depositAmount": 8000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1775454255588
  },
  {
    "id": "s_mock_9",
    "clientNumber": "009",
    "clientName": "Ramesh Thapa",
    "clientEmail": "",
    "clientPhone": "9897578550",
    "sessionType": "Maternity Photography",
    "date": "2026-02-26",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "27 Edited Photos",
    "deliverableDueDate": "2026-03-05",
    "isDelivered": true,
    "source": ClientSource.OTHER,
    "package": "Premium Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 15000,
      "depositAmount": 7500,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1769751855588
  },
  {
    "id": "s_mock_10",
    "clientNumber": "010",
    "clientName": "Suman Bhattarai",
    "clientEmail": "",
    "clientPhone": "9810420826",
    "sessionType": "Cake Smash",
    "date": "2026-05-26",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "33 Edited Photos",
    "deliverableDueDate": "2026-06-09",
    "isDelivered": false,
    "babyBirthday": "2025-05-26",
    "source": ClientSource.REFERRAL,
    "package": "Basic Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 31000,
      "remainingPaid": true
    },
    "createdAt": 1777873455588
  },
  {
    "id": "s_mock_11",
    "clientNumber": "011",
    "clientName": "Kiran Shah",
    "clientEmail": "kiran.shah@example.com",
    "clientPhone": "9890580436",
    "sessionType": "Newborn Photography",
    "date": "2026-03-17",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "28 Edited Photos",
    "deliverableDueDate": "2026-03-24",
    "isDelivered": true,
    "source": ClientSource.OTHER,
    "package": "Standard Newborn Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 31000,
      "depositAmount": 15500,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1773207855588
  },
  {
    "id": "s_mock_12",
    "clientNumber": "012",
    "clientName": "Niranjan Bhattarai",
    "clientEmail": "niranjan.bhattarai@example.com",
    "clientPhone": "9876393242",
    "sessionType": "Family Portrait",
    "date": "2026-03-26",
    "startTime": "17:00",
    "endTime": "19:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "57 Edited Photos",
    "deliverableDueDate": "2026-04-08",
    "isDelivered": true,
    "source": ClientSource.REFERRAL,
    "package": "Deluxe Family Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 20000,
      "remainingPaid": true
    },
    "createdAt": 1773467055588
  },
  {
    "id": "s_mock_13",
    "clientNumber": "013",
    "clientName": "Prabin Maharjan",
    "clientEmail": "prabin.maharjan@example.com",
    "clientPhone": "9829573260",
    "sessionType": "Family Portrait",
    "date": "2026-03-17",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "32 Edited Photos",
    "deliverableDueDate": "2026-03-31",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Basic Family Session",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 28000,
      "remainingPaid": true
    },
    "createdAt": 1772171055588
  },
  {
    "id": "s_mock_14",
    "clientNumber": "014",
    "clientName": "Anish Oli",
    "clientEmail": "anish.oli@example.com",
    "clientPhone": "9899112513",
    "sessionType": "Maternity Photography",
    "date": "2026-04-06",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "25 Edited Photos",
    "deliverableDueDate": "2026-04-26",
    "isDelivered": true,
    "source": ClientSource.WALK_IN,
    "package": "Premium Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 16000,
      "remainingPaid": true
    },
    "createdAt": 1773985455588
  },
  {
    "id": "s_mock_15",
    "clientNumber": "015",
    "clientName": "Suman KC",
    "clientEmail": "",
    "clientPhone": "9881923578",
    "sessionType": "Family Portrait",
    "date": "2026-05-15",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "54 Edited Photos",
    "deliverableDueDate": "2026-05-31",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Basic Family Session",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 34000,
      "remainingPaid": false
    },
    "createdAt": 1778391855588
  },
  {
    "id": "s_mock_16",
    "clientNumber": "016",
    "clientName": "Binod Sharma",
    "clientEmail": "binod.sharma@example.com",
    "clientPhone": "9869702050",
    "sessionType": "Maternity Photography",
    "date": "2026-04-08",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "28 Edited Photos",
    "deliverableDueDate": "2026-04-26",
    "isDelivered": false,
    "source": ClientSource.ADS,
    "package": "Premium Maternity Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 11000,
      "depositAmount": 5500,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1773207855588
  },
  {
    "id": "s_mock_17",
    "clientNumber": "017",
    "clientName": "Kiran Rai",
    "clientEmail": "kiran.rai@example.com",
    "clientPhone": "9835503811",
    "sessionType": "Newborn Photography",
    "date": "2026-03-04",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "34 Edited Photos",
    "deliverableDueDate": "2026-03-19",
    "isDelivered": true,
    "source": ClientSource.WALK_IN,
    "package": "Standard Newborn Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 26000,
      "remainingPaid": true
    },
    "createdAt": 1771652655588
  },
  {
    "id": "s_mock_18",
    "clientNumber": "018",
    "clientName": "Rita Thapa",
    "clientEmail": "",
    "clientPhone": "9821377626",
    "sessionType": "Maternity Photography",
    "date": "2026-04-07",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "46 Edited Photos",
    "deliverableDueDate": "2026-04-18",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Standard Maternity Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 16000,
      "remainingPaid": true
    },
    "createdAt": 1773985455588
  },
  {
    "id": "s_mock_19",
    "clientNumber": "019",
    "clientName": "Bimala Bhattarai",
    "clientEmail": "bimala.bhattarai@example.com",
    "clientPhone": "9824079958",
    "sessionType": "Family Portrait",
    "date": "2026-05-22",
    "startTime": "14:00",
    "endTime": "16:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "51 Edited Photos",
    "deliverableDueDate": "2026-06-09",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Standard Family Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 25000,
      "depositAmount": 12500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1778651055588
  },
  {
    "id": "s_mock_20",
    "clientNumber": "020",
    "clientName": "Kriti Bista",
    "clientEmail": "",
    "clientPhone": "9831727358",
    "sessionType": "Family Portrait",
    "date": "2026-03-29",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "18 Edited Photos",
    "deliverableDueDate": "2026-04-16",
    "isDelivered": true,
    "source": ClientSource.WALK_IN,
    "package": "Deluxe Family Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 25000,
      "remainingPaid": true
    },
    "createdAt": 1773985455588
  },
  {
    "id": "s_mock_21",
    "clientNumber": "021",
    "clientName": "Santosh KC",
    "clientEmail": "",
    "clientPhone": "9829920924",
    "sessionType": "Newborn Photography",
    "date": "2026-05-17",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "32 Edited Photos",
    "deliverableDueDate": "2026-06-02",
    "isDelivered": false,
    "source": ClientSource.REFERRAL,
    "package": "Standard Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 31000,
      "depositAmount": 15500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1778478255588
  },
  {
    "id": "s_mock_22",
    "clientNumber": "022",
    "clientName": "Prabin Adhikari",
    "clientEmail": "prabin.adhikari@example.com",
    "clientPhone": "9811870891",
    "sessionType": "Maternity Photography",
    "date": "2026-03-05",
    "startTime": "13:00",
    "endTime": "15:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "26 Edited Photos",
    "deliverableDueDate": "2026-03-14",
    "isDelivered": true,
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Standard Maternity Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 24000,
      "remainingPaid": true
    },
    "createdAt": 1772257455588
  },
  {
    "id": "s_mock_23",
    "clientNumber": "023",
    "clientName": "Sanjay Lama",
    "clientEmail": "sanjay.lama@example.com",
    "clientPhone": "9858870625",
    "sessionType": "Family Portrait",
    "date": "2026-02-22",
    "startTime": "15:00",
    "endTime": "17:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "53 Edited Photos",
    "deliverableDueDate": "2026-03-06",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Basic Family Session",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 19000,
      "depositAmount": 9500,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1769751855588
  },
  {
    "id": "s_mock_24",
    "clientNumber": "024",
    "clientName": "Santosh Magar",
    "clientEmail": "santosh.magar@example.com",
    "clientPhone": "9877824614",
    "sessionType": "Family Portrait",
    "date": "2026-04-07",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "25 Edited Photos",
    "deliverableDueDate": "2026-04-28",
    "isDelivered": false,
    "source": ClientSource.ADS,
    "package": "Standard Family Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 20000,
      "depositAmount": 10000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1773121455588
  },
  {
    "id": "s_mock_25",
    "clientNumber": "025",
    "clientName": "Niranjan Karki",
    "clientEmail": "",
    "clientPhone": "9865738962",
    "sessionType": "Cake Smash",
    "date": "2026-05-19",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "22 Edited Photos",
    "deliverableDueDate": "2026-06-09",
    "isDelivered": false,
    "babyBirthday": "2025-05-19",
    "source": ClientSource.ADS,
    "package": "Basic Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 11000,
      "depositAmount": 5500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1778651055588
  },
  {
    "id": "s_mock_26",
    "clientNumber": "026",
    "clientName": "Prabin Shah",
    "clientEmail": "prabin.shah@example.com",
    "clientPhone": "9829984243",
    "sessionType": "Newborn Photography",
    "date": "2026-03-15",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "20 Edited Photos",
    "deliverableDueDate": "2026-04-05",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Premium Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 24000,
      "depositAmount": 12000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1772775855588
  },
  {
    "id": "s_mock_27",
    "clientNumber": "027",
    "clientName": "Rita Bhattarai",
    "clientEmail": "rita.bhattarai@example.com",
    "clientPhone": "9899403466",
    "sessionType": "Newborn Photography",
    "date": "2026-04-21",
    "startTime": "15:00",
    "endTime": "17:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "60 Edited Photos",
    "deliverableDueDate": "2026-05-12",
    "isDelivered": false,
    "source": ClientSource.REFERRAL,
    "package": "Basic Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 10000,
      "depositAmount": 5000,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1774676655588
  },
  {
    "id": "s_mock_28",
    "clientNumber": "028",
    "clientName": "Diya Adhikari",
    "clientEmail": "diya.adhikari@example.com",
    "clientPhone": "9873384776",
    "sessionType": "Maternity Photography",
    "date": "2026-03-22",
    "startTime": "13:00",
    "endTime": "15:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "29 Edited Photos",
    "deliverableDueDate": "2026-03-29",
    "isDelivered": true,
    "source": ClientSource.ADS,
    "package": "Standard Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 15000,
      "remainingPaid": true
    },
    "createdAt": 1773380655588
  },
  {
    "id": "s_mock_29",
    "clientNumber": "029",
    "clientName": "Roshan Thapa",
    "clientEmail": "",
    "clientPhone": "9876611185",
    "sessionType": "Family Portrait",
    "date": "2026-05-04",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "28 Edited Photos",
    "deliverableDueDate": "2026-05-13",
    "isDelivered": false,
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Deluxe Family Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 12000,
      "remainingPaid": true
    },
    "createdAt": 1777009455588
  },
  {
    "id": "s_mock_30",
    "clientNumber": "030",
    "clientName": "Alisha Gautam",
    "clientEmail": "alisha.gautam@example.com",
    "clientPhone": "9859511232",
    "sessionType": "Maternity Photography",
    "date": "2026-03-15",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "20 Edited Photos",
    "deliverableDueDate": "2026-03-22",
    "isDelivered": true,
    "source": ClientSource.WALK_IN,
    "package": "Premium Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 11000,
      "remainingPaid": false
    },
    "createdAt": 1771393455588
  },
  {
    "id": "s_mock_31",
    "clientNumber": "031",
    "clientName": "Milan Lama",
    "clientEmail": "",
    "clientPhone": "9887505103",
    "sessionType": "Cake Smash",
    "date": "2026-03-04",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "40 Edited Photos",
    "deliverableDueDate": "2026-03-11",
    "isDelivered": true,
    "babyBirthday": "2025-03-04",
    "source": ClientSource.WALK_IN,
    "package": "Basic Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 18000,
      "depositAmount": 9000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1770702255588
  },
  {
    "id": "s_mock_32",
    "clientNumber": "032",
    "clientName": "Kriti KC",
    "clientEmail": "",
    "clientPhone": "9896100046",
    "sessionType": "Newborn Photography",
    "date": "2026-02-22",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "47 Edited Photos",
    "deliverableDueDate": "2026-03-15",
    "isDelivered": true,
    "source": ClientSource.WALK_IN,
    "package": "Basic Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 29000,
      "remainingPaid": true
    },
    "createdAt": 1770270255588
  },
  {
    "id": "s_mock_33",
    "clientNumber": "033",
    "clientName": "Rajendra Karki",
    "clientEmail": "rajendra.karki@example.com",
    "clientPhone": "9889524332",
    "sessionType": "Cake Smash",
    "date": "2026-05-27",
    "startTime": "14:00",
    "endTime": "16:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "46 Edited Photos",
    "deliverableDueDate": "2026-06-06",
    "isDelivered": false,
    "babyBirthday": "2025-05-27",
    "source": ClientSource.WALK_IN,
    "package": "Basic Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 31000,
      "remainingPaid": true
    },
    "createdAt": 1778651055588
  },
  {
    "id": "s_mock_34",
    "clientNumber": "034",
    "clientName": "Kabita Chaudhary",
    "clientEmail": "kabita.chaudhary@example.com",
    "clientPhone": "9820974933",
    "sessionType": "Cake Smash",
    "date": "2026-06-01",
    "startTime": "15:00",
    "endTime": "17:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "47 Edited Photos",
    "deliverableDueDate": "2026-06-09",
    "isDelivered": false,
    "babyBirthday": "2025-06-01",
    "source": ClientSource.WALK_IN,
    "package": "Basic Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 24000,
      "depositAmount": 12000,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1778132655588
  },
  {
    "id": "s_mock_35",
    "clientNumber": "035",
    "clientName": "Bimala Shrestha",
    "clientEmail": "bimala.shrestha@example.com",
    "clientPhone": "9828648593",
    "sessionType": "Family Portrait",
    "date": "2026-03-17",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "50 Edited Photos",
    "deliverableDueDate": "2026-04-02",
    "isDelivered": true,
    "source": ClientSource.ADS,
    "package": "Deluxe Family Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 15000,
      "remainingPaid": true
    },
    "createdAt": 1771134255588
  },
  {
    "id": "s_mock_36",
    "clientNumber": "036",
    "clientName": "Suman Karki",
    "clientEmail": "suman.karki@example.com",
    "clientPhone": "9824935749",
    "sessionType": "Family Portrait",
    "date": "2026-04-20",
    "startTime": "15:00",
    "endTime": "17:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "37 Edited Photos",
    "deliverableDueDate": "2026-05-09",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Basic Family Session",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 26000,
      "remainingPaid": true
    },
    "createdAt": 1774244655588
  },
  {
    "id": "s_mock_37",
    "clientNumber": "037",
    "clientName": "Prabin Magar",
    "clientEmail": "prabin.magar@example.com",
    "clientPhone": "9832350116",
    "sessionType": "Family Portrait",
    "date": "2026-03-17",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "34 Edited Photos",
    "deliverableDueDate": "2026-03-25",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Deluxe Family Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 18000,
      "remainingPaid": false
    },
    "createdAt": 1772171055588
  },
  {
    "id": "s_mock_38",
    "clientNumber": "038",
    "clientName": "Alisha Shah",
    "clientEmail": "alisha.shah@example.com",
    "clientPhone": "9842859330",
    "sessionType": "Cake Smash",
    "date": "2026-03-30",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": false,
    "isDeleted": true,
    "deliverables": "52 Edited Photos",
    "deliverableDueDate": "2026-04-18",
    "isDelivered": true,
    "babyBirthday": "2025-03-30",
    "source": ClientSource.OTHER,
    "package": "Basic Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 18000,
      "depositAmount": 9000,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1773467055588
  },
  {
    "id": "s_mock_39",
    "clientNumber": "039",
    "clientName": "Bikash Sharma",
    "clientEmail": "bikash.sharma@example.com",
    "clientPhone": "9827751740",
    "sessionType": "Cake Smash",
    "date": "2026-03-09",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "47 Edited Photos",
    "deliverableDueDate": "2026-03-18",
    "isDelivered": true,
    "babyBirthday": "2025-03-09",
    "source": ClientSource.OTHER,
    "package": "Deluxe Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 11000,
      "depositAmount": 5500,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1770961455588
  },
  {
    "id": "s_mock_40",
    "clientNumber": "040",
    "clientName": "Bikash Karki",
    "clientEmail": "bikash.karki@example.com",
    "clientPhone": "9862042573",
    "sessionType": "Cake Smash",
    "date": "2026-03-05",
    "startTime": "14:00",
    "endTime": "16:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "52 Edited Photos",
    "deliverableDueDate": "2026-03-15",
    "isDelivered": false,
    "babyBirthday": "2025-03-05",
    "source": ClientSource.WALK_IN,
    "package": "Deluxe Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 22000,
      "depositAmount": 11000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1771911855588
  },
  {
    "id": "s_mock_41",
    "clientNumber": "041",
    "clientName": "Srijana Khadka",
    "clientEmail": "srijana.khadka@example.com",
    "clientPhone": "9866271558",
    "sessionType": "Family Portrait",
    "date": "2026-04-01",
    "startTime": "13:00",
    "endTime": "15:00",
    "isCustomSlot": true,
    "isDeleted": true,
    "deliverables": "23 Edited Photos",
    "deliverableDueDate": "2026-04-16",
    "isDelivered": true,
    "source": ClientSource.REFERRAL,
    "package": "Standard Family Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 19000,
      "depositAmount": 9500,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1773726255588
  },
  {
    "id": "s_mock_42",
    "clientNumber": "042",
    "clientName": "Puja Chaudhary",
    "clientEmail": "puja.chaudhary@example.com",
    "clientPhone": "9856449131",
    "sessionType": "Newborn Photography",
    "date": "2026-02-24",
    "startTime": "17:00",
    "endTime": "19:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "31 Edited Photos",
    "deliverableDueDate": "2026-03-12",
    "isDelivered": true,
    "source": ClientSource.WALK_IN,
    "package": "Basic Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 17000,
      "depositAmount": 8500,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1770097455588
  },
  {
    "id": "s_mock_43",
    "clientNumber": "043",
    "clientName": "Sneha Bista",
    "clientEmail": "sneha.bista@example.com",
    "clientPhone": "9886905530",
    "sessionType": "Maternity Photography",
    "date": "2026-05-19",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "47 Edited Photos",
    "deliverableDueDate": "2026-06-01",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Standard Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 30000,
      "depositAmount": 15000,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1777441455588
  },
  {
    "id": "s_mock_44",
    "clientNumber": "044",
    "clientName": "Kabita Maharjan",
    "clientEmail": "kabita.maharjan@example.com",
    "clientPhone": "9877880442",
    "sessionType": "Family Portrait",
    "date": "2026-03-19",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "44 Edited Photos",
    "deliverableDueDate": "2026-04-06",
    "isDelivered": true,
    "source": ClientSource.ADS,
    "package": "Basic Family Session",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 22000,
      "remainingPaid": true
    },
    "createdAt": 1773380655588
  },
  {
    "id": "s_mock_45",
    "clientNumber": "045",
    "clientName": "Binod Rai",
    "clientEmail": "",
    "clientPhone": "9821658095",
    "sessionType": "Cake Smash",
    "date": "2026-06-01",
    "startTime": "15:00",
    "endTime": "17:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "53 Edited Photos",
    "deliverableDueDate": "2026-06-20",
    "isDelivered": false,
    "babyBirthday": "2025-06-01",
    "source": ClientSource.ADS,
    "package": "Basic Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 34000,
      "depositAmount": 17000,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1779860655588
  },
  {
    "id": "s_mock_46",
    "clientNumber": "046",
    "clientName": "Sabina Sharma",
    "clientEmail": "sabina.sharma@example.com",
    "clientPhone": "9874870564",
    "sessionType": "Maternity Photography",
    "date": "2026-04-24",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": true,
    "isDeleted": true,
    "deliverables": "29 Edited Photos",
    "deliverableDueDate": "2026-05-08",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Premium Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 20000,
      "remainingPaid": false
    },
    "createdAt": 1775886255588
  },
  {
    "id": "s_mock_47",
    "clientNumber": "047",
    "clientName": "Alisha Sharma",
    "clientEmail": "",
    "clientPhone": "9852352185",
    "sessionType": "Family Portrait",
    "date": "2026-04-23",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "49 Edited Photos",
    "deliverableDueDate": "2026-05-11",
    "isDelivered": false,
    "source": ClientSource.ADS,
    "package": "Basic Family Session",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 15000,
      "depositAmount": 7500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1774935855588
  },
  {
    "id": "s_mock_48",
    "clientNumber": "048",
    "clientName": "Ramesh Chaudhary",
    "clientEmail": "ramesh.chaudhary@example.com",
    "clientPhone": "9896723152",
    "sessionType": "Cake Smash",
    "date": "2026-03-26",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "18 Edited Photos",
    "deliverableDueDate": "2026-04-11",
    "isDelivered": true,
    "babyBirthday": "2025-03-26",
    "source": ClientSource.OTHER,
    "package": "Basic Cake Smash",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 30000,
      "depositAmount": 15000,
      "depositPaid": false,
      "remainingPaid": true
    },
    "createdAt": 1774071855588
  },
  {
    "id": "s_mock_49",
    "clientNumber": "049",
    "clientName": "Kabita Oli",
    "clientEmail": "kabita.oli@example.com",
    "clientPhone": "9835265236",
    "sessionType": "Maternity Photography",
    "date": "2026-04-03",
    "startTime": "15:00",
    "endTime": "17:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "29 Edited Photos",
    "deliverableDueDate": "2026-04-18",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Premium Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 29000,
      "remainingPaid": false
    },
    "createdAt": 1773467055588
  },
  {
    "id": "s_mock_50",
    "clientNumber": "050",
    "clientName": "Kabita Rai",
    "clientEmail": "kabita.rai@example.com",
    "clientPhone": "9872615160",
    "sessionType": "Newborn Photography",
    "date": "2026-02-28",
    "startTime": "14:00",
    "endTime": "16:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "52 Edited Photos",
    "deliverableDueDate": "2026-03-09",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Basic Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 11000,
      "depositAmount": 5500,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1770270255588
  },
  {
    "id": "s_mock_51",
    "clientNumber": "051",
    "clientName": "Alisha Thapa",
    "clientEmail": "alisha.thapa@example.com",
    "clientPhone": "9890672902",
    "sessionType": "Family Portrait",
    "date": "2026-05-24",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": true,
    "deliverables": "51 Edited Photos",
    "deliverableDueDate": "2026-06-09",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Basic Family Session",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 11000,
      "remainingPaid": false
    },
    "createdAt": 1779169455588
  },
  {
    "id": "s_mock_52",
    "clientNumber": "052",
    "clientName": "Kabita Thapa",
    "clientEmail": "",
    "clientPhone": "9877379417",
    "sessionType": "Maternity Photography",
    "date": "2026-05-26",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "40 Edited Photos",
    "deliverableDueDate": "2026-06-07",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Standard Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 14000,
      "depositAmount": 7000,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1778564655588
  },
  {
    "id": "s_mock_53",
    "clientNumber": "053",
    "clientName": "Ramesh Thapa",
    "clientEmail": "ramesh.thapa@example.com",
    "clientPhone": "9895138366",
    "sessionType": "Maternity Photography",
    "date": "2026-04-12",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "49 Edited Photos",
    "deliverableDueDate": "2026-04-27",
    "isDelivered": false,
    "source": ClientSource.REFERRAL,
    "package": "Standard Maternity Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 18000,
      "depositAmount": 9000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1775195055588
  },
  {
    "id": "s_mock_54",
    "clientNumber": "054",
    "clientName": "Manisha Lama",
    "clientEmail": "manisha.lama@example.com",
    "clientPhone": "9836390925",
    "sessionType": "Newborn Photography",
    "date": "2026-05-16",
    "startTime": "16:00",
    "endTime": "18:00",
    "isCustomSlot": true,
    "isDeleted": false,
    "deliverables": "17 Edited Photos",
    "deliverableDueDate": "2026-05-30",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Premium Newborn Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 16000,
      "remainingPaid": false
    },
    "createdAt": 1777268655588
  },
  {
    "id": "s_mock_55",
    "clientNumber": "055",
    "clientName": "Rita Rai",
    "clientEmail": "",
    "clientPhone": "9896229716",
    "sessionType": "Family Portrait",
    "date": "2026-05-27",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "48 Edited Photos",
    "deliverableDueDate": "2026-06-13",
    "isDelivered": false,
    "source": ClientSource.SOCIAL_MEDIA,
    "package": "Deluxe Family Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 19000,
      "depositAmount": 9500,
      "depositPaid": true,
      "remainingPaid": false
    },
    "createdAt": 1777614255588
  },
  {
    "id": "s_mock_56",
    "clientNumber": "056",
    "clientName": "Srijana Shrestha",
    "clientEmail": "",
    "clientPhone": "9817346947",
    "sessionType": "Family Portrait",
    "date": "2026-05-22",
    "startTime": "15:00",
    "endTime": "17:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "34 Edited Photos",
    "deliverableDueDate": "2026-05-29",
    "isDelivered": false,
    "source": ClientSource.ADS,
    "package": "Standard Family Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 13000,
      "depositAmount": 6500,
      "depositPaid": false,
      "remainingPaid": false
    },
    "createdAt": 1777959855588
  },
  {
    "id": "s_mock_57",
    "clientNumber": "057",
    "clientName": "Aarohi Lama",
    "clientEmail": "aarohi.lama@example.com",
    "clientPhone": "9823633996",
    "sessionType": "Cake Smash",
    "date": "2026-04-04",
    "startTime": "12:00",
    "endTime": "14:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "49 Edited Photos",
    "deliverableDueDate": "2026-04-25",
    "isDelivered": true,
    "babyBirthday": "2025-04-04",
    "source": ClientSource.REFERRAL,
    "package": "Deluxe Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 16000,
      "depositAmount": 8000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1774071855588
  },
  {
    "id": "s_mock_58",
    "clientNumber": "058",
    "clientName": "Santosh Karki",
    "clientEmail": "santosh.karki@example.com",
    "clientPhone": "9845497478",
    "sessionType": "Family Portrait",
    "date": "2026-05-14",
    "startTime": "17:00",
    "endTime": "19:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "25 Edited Photos",
    "deliverableDueDate": "2026-06-01",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Basic Family Session",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 14000,
      "remainingPaid": false
    },
    "createdAt": 1776577455588
  },
  {
    "id": "s_mock_59",
    "clientNumber": "059",
    "clientName": "Diya Magar",
    "clientEmail": "diya.magar@example.com",
    "clientPhone": "9895869786",
    "sessionType": "Maternity Photography",
    "date": "2026-03-11",
    "startTime": "13:00",
    "endTime": "15:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "44 Edited Photos",
    "deliverableDueDate": "2026-03-29",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Standard Maternity Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 27000,
      "remainingPaid": true
    },
    "createdAt": 1772430255588
  },
  {
    "id": "s_mock_60",
    "clientNumber": "060",
    "clientName": "Milan Gurung",
    "clientEmail": "",
    "clientPhone": "9824182684",
    "sessionType": "Cake Smash",
    "date": "2026-05-31",
    "startTime": "11:00",
    "endTime": "13:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "20 Edited Photos",
    "deliverableDueDate": "2026-06-15",
    "isDelivered": false,
    "babyBirthday": "2025-05-31",
    "source": ClientSource.REFERRAL,
    "package": "Deluxe Cake Smash",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 18000,
      "remainingPaid": false
    },
    "createdAt": 1778737455588
  },
  {
    "id": "s_mock_61",
    "clientNumber": "061",
    "clientName": "Prabin Lama",
    "clientEmail": "",
    "clientPhone": "9812934919",
    "sessionType": "Maternity Photography",
    "date": "2026-03-16",
    "startTime": "14:00",
    "endTime": "16:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "17 Edited Photos",
    "deliverableDueDate": "2026-03-30",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Standard Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 24000,
      "depositAmount": 12000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1772689455588
  },
  {
    "id": "s_mock_62",
    "clientNumber": "062",
    "clientName": "Kiran Magar",
    "clientEmail": "kiran.magar@example.com",
    "clientPhone": "9821094449",
    "sessionType": "Maternity Photography",
    "date": "2026-03-09",
    "startTime": "17:00",
    "endTime": "19:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "17 Edited Photos",
    "deliverableDueDate": "2026-03-24",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Standard Maternity Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 30000,
      "remainingPaid": true
    },
    "createdAt": 1771220655588
  },
  {
    "id": "s_mock_63",
    "clientNumber": "063",
    "clientName": "Prakash Lama",
    "clientEmail": "prakash.lama@example.com",
    "clientPhone": "9871530774",
    "sessionType": "Family Portrait",
    "date": "2026-04-06",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "44 Edited Photos",
    "deliverableDueDate": "2026-04-24",
    "isDelivered": true,
    "source": ClientSource.ADS,
    "package": "Deluxe Family Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 17000,
      "remainingPaid": true
    },
    "createdAt": 1774503855588
  },
  {
    "id": "s_mock_64",
    "clientNumber": "064",
    "clientName": "Kabita Sharma",
    "clientEmail": "",
    "clientPhone": "9882788245",
    "sessionType": "Newborn Photography",
    "date": "2026-04-13",
    "startTime": "09:00",
    "endTime": "11:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "42 Edited Photos",
    "deliverableDueDate": "2026-04-27",
    "isDelivered": false,
    "source": ClientSource.WALK_IN,
    "package": "Standard Newborn Package",
    "notes": "Client requested specific edits. Needs attention to detail.",
    "payment": {
      "type": PaymentType.SPLIT,
      "totalAmount": 16000,
      "depositAmount": 8000,
      "depositPaid": true,
      "remainingPaid": true
    },
    "createdAt": 1774590255588
  },
  {
    "id": "s_mock_65",
    "clientNumber": "065",
    "clientName": "Bimala Bhattarai",
    "clientEmail": "",
    "clientPhone": "9895462091",
    "sessionType": "Newborn Photography",
    "date": "2026-03-08",
    "startTime": "10:00",
    "endTime": "12:00",
    "isCustomSlot": false,
    "isDeleted": false,
    "deliverables": "19 Edited Photos",
    "deliverableDueDate": "2026-03-26",
    "isDelivered": false,
    "source": ClientSource.OTHER,
    "package": "Basic Newborn Package",
    "notes": "",
    "payment": {
      "type": PaymentType.FULL,
      "totalAmount": 18000,
      "remainingPaid": true
    },
    "createdAt": 1771047855588
  }
];

export const mockLeads: Lead[] = [
  {
    "id": "l_mock_1",
    "name": "Srijana Chaudhary",
    "phone": "9832445528",
    "email": "",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-03-31",
    "createdAt": "2026-03-24T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_2",
    "name": "Sameer Thapa",
    "phone": "9852399966",
    "email": "sameer.thapa@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-03-28",
    "createdAt": "2026-03-24T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_3",
    "name": "Kabita Shah",
    "phone": "9884063637",
    "email": "",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-08",
    "createdAt": "2026-04-07T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_4",
    "name": "Sanjay Chaudhary",
    "phone": "9826893445",
    "email": "sanjay.chaudhary@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-19",
    "createdAt": "2026-04-16T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_5",
    "name": "Puja Gurung",
    "phone": "9872470111",
    "email": "puja.gurung@example.com",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-29",
    "createdAt": "2026-04-24T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_6",
    "name": "Kiran Chaudhary",
    "phone": "9826939203",
    "email": "kiran.chaudhary@example.com",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-25",
    "createdAt": "2026-04-18T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_7",
    "name": "Roshan Rai",
    "phone": "9880229699",
    "email": "roshan.rai@example.com",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-05-01",
    "createdAt": "2026-04-25T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_8",
    "name": "Ashish Bista",
    "phone": "9846091388",
    "email": "",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-13",
    "createdAt": "2026-04-11T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_9",
    "name": "Alisha Shrestha",
    "phone": "9885913579",
    "email": "alisha.shrestha@example.com",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-16",
    "createdAt": "2026-04-15T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_10",
    "name": "Sanjay Khadka",
    "phone": "9858812995",
    "email": "sanjay.khadka@example.com",
    "source": LeadSource.WALK_IN,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-16",
    "createdAt": "2026-04-09T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_11",
    "name": "Rajendra Chaudhary",
    "phone": "9876533355",
    "email": "",
    "source": LeadSource.WALK_IN,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-09",
    "createdAt": "2026-04-04T05:44:15.588Z",
    "isDeleted": true
  },
  {
    "id": "l_mock_12",
    "name": "Aarohi Tamang",
    "phone": "9885733064",
    "email": "aarohi.tamang@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-18",
    "createdAt": "2026-04-17T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_13",
    "name": "Anish Shrestha",
    "phone": "9877373434",
    "email": "anish.shrestha@example.com",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-10",
    "createdAt": "2026-04-09T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_14",
    "name": "Sanjay Thapa",
    "phone": "9829337706",
    "email": "sanjay.thapa@example.com",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-22",
    "createdAt": "2026-04-19T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_15",
    "name": "Anish Bhattarai",
    "phone": "9880126173",
    "email": "anish.bhattarai@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-16",
    "createdAt": "2026-04-13T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_16",
    "name": "Saurav Bhattarai",
    "phone": "9828214041",
    "email": "saurav.bhattarai@example.com",
    "source": LeadSource.WALK_IN,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-05-03",
    "createdAt": "2026-04-26T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_17",
    "name": "Bimala Sharma",
    "phone": "9818288856",
    "email": "",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-02",
    "createdAt": "2026-03-27T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_18",
    "name": "Puja Gurung",
    "phone": "9887606480",
    "email": "puja.gurung@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-28",
    "createdAt": "2026-04-21T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_19",
    "name": "Ramesh Thapa",
    "phone": "9874857756",
    "email": "",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-18",
    "createdAt": "2026-04-13T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_20",
    "name": "Rita Lama",
    "phone": "9815229063",
    "email": "rita.lama@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-20",
    "createdAt": "2026-04-16T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_21",
    "name": "Kriti Gurung",
    "phone": "9873998520",
    "email": "",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-28",
    "createdAt": "2026-04-25T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_22",
    "name": "Anish Magar",
    "phone": "9885501416",
    "email": "",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-18",
    "createdAt": "2026-04-14T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_23",
    "name": "Santosh Chaudhary",
    "phone": "9852092344",
    "email": "",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-10",
    "createdAt": "2026-04-04T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_24",
    "name": "Kiran Tamang",
    "phone": "9836451712",
    "email": "",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-02",
    "createdAt": "2026-03-28T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_25",
    "name": "Sameer Shrestha",
    "phone": "9863400668",
    "email": "sameer.shrestha@example.com",
    "source": LeadSource.WALK_IN,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-10",
    "createdAt": "2026-04-09T05:44:15.588Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_26",
    "name": "Prakash Bista",
    "phone": "9828463917",
    "email": "prakash.bista@example.com",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-04",
    "createdAt": "2026-04-01T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_27",
    "name": "Ramesh Bhattarai",
    "phone": "9820749262",
    "email": "",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-18",
    "createdAt": "2026-04-14T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_28",
    "name": "Bimala Thapa",
    "phone": "9850440274",
    "email": "",
    "source": LeadSource.WALK_IN,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-25",
    "createdAt": "2026-04-20T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_29",
    "name": "Sabina Oli",
    "phone": "9869831357",
    "email": "sabina.oli@example.com",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-25",
    "createdAt": "2026-04-23T05:44:15.589Z",
    "isDeleted": true
  },
  {
    "id": "l_mock_30",
    "name": "Saurav Adhikari",
    "phone": "9897591637",
    "email": "",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-04",
    "createdAt": "2026-03-30T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_31",
    "name": "Bimala Maharjan",
    "phone": "9872432823",
    "email": "bimala.maharjan@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-01",
    "createdAt": "2026-03-31T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_32",
    "name": "Diya Bhattarai",
    "phone": "9862873077",
    "email": "diya.bhattarai@example.com",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-04",
    "createdAt": "2026-04-02T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_33",
    "name": "Niranjan Pandey",
    "phone": "9849143294",
    "email": "niranjan.pandey@example.com",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-09",
    "createdAt": "2026-04-05T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_34",
    "name": "Santosh Maharjan",
    "phone": "9811538289",
    "email": "santosh.maharjan@example.com",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-03-26",
    "createdAt": "2026-03-24T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_35",
    "name": "Roshan Gurung",
    "phone": "9841579325",
    "email": "roshan.gurung@example.com",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-03-29",
    "createdAt": "2026-03-24T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_36",
    "name": "Milan Bhattarai",
    "phone": "9822586536",
    "email": "milan.bhattarai@example.com",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-15",
    "createdAt": "2026-04-08T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_37",
    "name": "Diya Shrestha",
    "phone": "9858890083",
    "email": "",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-16",
    "createdAt": "2026-04-09T05:44:15.589Z",
    "isDeleted": true
  },
  {
    "id": "l_mock_38",
    "name": "Prabin Sharma",
    "phone": "9850214330",
    "email": "",
    "source": LeadSource.META,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-10",
    "createdAt": "2026-04-06T05:44:15.589Z",
    "isDeleted": true
  },
  {
    "id": "l_mock_39",
    "name": "Diya Tamang",
    "phone": "9830603994",
    "email": "",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-12",
    "createdAt": "2026-04-10T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_40",
    "name": "Alisha Gautam",
    "phone": "9897029751",
    "email": "",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": false,
    "followUpDate": "2026-04-30",
    "createdAt": "2026-04-23T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_41",
    "name": "Srijana Bista",
    "phone": "9822700445",
    "email": "srijana.bista@example.com",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-27",
    "createdAt": "2026-04-21T05:44:15.589Z",
    "isDeleted": true
  },
  {
    "id": "l_mock_42",
    "name": "Binod Magar",
    "phone": "9821414039",
    "email": "",
    "source": LeadSource.TIKTOK,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-21",
    "createdAt": "2026-04-18T05:44:15.589Z",
    "isDeleted": true
  },
  {
    "id": "l_mock_43",
    "name": "Sameer Bhattarai",
    "phone": "9844126909",
    "email": "sameer.bhattarai@example.com",
    "source": LeadSource.GOOGLE,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-16",
    "createdAt": "2026-04-10T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_44",
    "name": "Sneha Rai",
    "phone": "9817589166",
    "email": "sneha.rai@example.com",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Very interested.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-25",
    "createdAt": "2026-04-21T05:44:15.589Z",
    "isDeleted": false
  },
  {
    "id": "l_mock_45",
    "name": "Suman Chaudhary",
    "phone": "9832954664",
    "email": "suman.chaudhary@example.com",
    "source": ClientSource.OTHER,
    "note": "Inquired about packages and pricing. Still deciding.",
    "isFollowUpRequired": true,
    "followUpDate": "2026-04-06",
    "createdAt": "2026-04-03T05:44:15.589Z",
    "isDeleted": false
  }
];
